# AI Methods I 
###### Group Members: Ugochinyere Megwa, Sneha Sachin Shenoy, Álvaro Miñé
###### Faculty: Salvador

## Apartment Cost in New York City

#### Overview

This data was downloaded from Kaggle. Our aim is to analyse the data, clean it, explore it and model it.

In [ ]:
# %pip install "kagglehub[pandas-datasets]" pandas numpy matplotlib seaborn scikit-learn

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../figures/apartment_data.csv')

In [5]:
df_clean = df.copy()

In [6]:
print(df)

           Job #    Borough House #          Street Name  Block  Lot    Bin #  \
0      123768976  MANHATTAN    1598           2ND AVENUE   1545   49  1049907
1      140922893  MANHATTAN     160              E 89 ST   1517   43  1048094
2      301773579   BROOKLYN      65         GATES AVENUE   1962   86  3056039
3      301976057   BROOKLYN    1401         OCEAN AVENUE   7584   35  3206621
4      301989276   BROOKLYN     154         NOBLE STREET   2573   10  3065099
...          ...        ...     ...                  ...    ...  ...      ...
19608  122923649  MANHATTAN     315     WEST 33RD STREET    757   22  1013552
19609  121090112  MANHATTAN     110         DUANE STREET    150   22  1001645
19610  102937342  MANHATTAN     166          BANK STREET    638    4  1078335
19611  200838558      BRONX    2762  KINGSBRIDGE TERRACE   3253   90  2015521
19612  301429158   BROOKLYN     802        HOWARD AVENUE   3565   42  3081797

      Job Type  Community - Board Curb Cut Fully Permitted Initial Cost  \
0           A2                108      NaN             NaN   $65,000.00
1           A2                108      NaN      07/14/2020   $85,000.00
2           A1                302      NaN      05/23/2007   $60,000.00
3           A2                314      NaN      02/28/2006   $75,000.00
4           A1                301      NaN      09/29/2006   $40,000.00
...        ...                ...      ...             ...          ...
19608       A2                104      NaN      03/21/2017   $60,000.00
19609       A2                101      NaN      07/17/2012   $40,000.00
19610       A2                102      NaN      02/07/2001   $80,000.00
19611       A2                208      NaN             NaN   $40,000.00
19612       A2                316      NaN             NaN   $60,000.00

       Proposed Zoning Sqft Horizontal Enlrgmt Vertical Enlrgmt  \
0                         0                NaN              NaN
1                         0                NaN              NaN
2                         0                NaN              NaN
3                         0                NaN              NaN
4                         0                NaN              NaN
...                     ...                ...              ...
19608                     0                NaN              NaN
19609                     0                NaN              NaN
19610                     0                NaN              NaN
19611                     0                NaN              NaN
19612                     0                NaN              NaN

       Enlargement SQ Footage Zoning Dist1  \
0                           0         C1-9
1                           0          R8B
2                           0           R6
3                           0          NaN
4                           0         C4-3
...                       ...          ...
19608                       0         C6-4
19609                       0        C6-2A
19610                       0         C6-2
19611                       0           R6
19612                       0           R6

                                         Job Description
0      INTERIOR RENOVATION TO COMBINE APARTMENT 2E AN...
1      HEREBY FILING APPLICATION FOR THE INTERIOR REN...
2      Change existing four story and basement brick ...
3      COMBINING OF APARTMENT 4A &amp; 4L.NO CHANGEIN...
4      New C of O for existing building. New duplex a...
...                                                  ...
19608  RENOVATION OF APARTMENTS 8N &amp; 12A. ARCHITE...
19609  APARTMENT RENVOATION AT APT #4R. DEMOLISH AND ...
19610  Interior renovation of an existing apartment. ...
19611  Proposed to renovate existing apartments. No c...
19612  PROPOSE RENOVATE EXISTING CLASS 'A' APARTMENT ...

[19613 rows x 18 columns]

In [7]:
df

,Job #,Borough,House #,Street Name,Block,Lot,Bin #,Job Type,Community - Board,Curb Cut,Fully Permitted,Initial Cost,Proposed Zoning Sqft,Horizontal Enlrgmt,Vertical Enlrgmt,Enlargement SQ Footage,Zoning Dist1,Job Description
0,123768976,MANHATTAN,1598,2ND AVENUE,1545,49,1049907,A2,108,NaN,NaN,"$65,000.00",0,NaN,NaN,0,C1-9,INTERIOR RENOVATION TO COMBINE APARTMENT 2E AN...
1,140922893,MANHATTAN,160,E 89 ST,1517,43,1048094,A2,108,NaN,07/14/2020,"$85,000.00",0,NaN,NaN,0,R8B,HEREBY FILING APPLICATION FOR THE INTERIOR REN...
2,301773579,BROOKLYN,65,GATES AVENUE,1962,86,3056039,A1,302,NaN,05/23/2007,"$60,000.00",0,NaN,NaN,0,R6,Change existing four story and basement brick ...
3,301976057,BROOKLYN,1401,OCEAN AVENUE,7584,35,3206621,A2,314,NaN,02/28/2006,"$75,000.00",0,NaN,NaN,0,NaN,COMBINING OF APARTMENT 4A &amp; 4L.NO CHANGEIN...
4,301989276,BROOKLYN,154,NOBLE STREET,2573,10,3065099,A1,301,NaN,09/29/2006,"$40,000.00",0,NaN,NaN,0,C4-3,New C of O for existing building. New duplex a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19608,122923649,MANHATTAN,315,WEST 33RD STREET,757,22,1013552,A2,104,NaN,03/21/2017,"$60,000.00",0,NaN,NaN,0,C6-4,RENOVATION OF APARTMENTS 8N &amp; 12A. ARCHITE...
19609,121090112,MANHATTAN,110,DUANE STREET,150,22,1001645,A2,101,NaN,07/17/2012,"$40,000.00",0,NaN,NaN,0,C6-2A,APARTMENT RENVOATION AT APT #4R. DEMOLISH AND ...
19610,102937342,MANHATTAN,166,BANK STREET,638,4,1078335,A2,102,NaN,02/07/2001,"$80,000.00",0,NaN,NaN,0,C6-2,Interior renovation of an existing apartment. ...
19611,200838558,BRONX,2762,KINGSBRIDGE TERRACE,3253,90,2015521,A2,208,NaN,NaN,"$40,000.00",0,NaN,NaN,0,R6,Proposed to renovate existing apartments. No c...
19612,301429158,BROOKLYN,802,HOWARD AVENUE,3565,42,3081797,A2,316,NaN,NaN,"$60,000.00",0,NaN,NaN,0,R6,PROPOSE RENOVATE EXISTING CLASS 'A' APARTMENT ...

In [24]:
df = df.drop(['Curb Cut', 'Proposed Zoning Sqft', 'Horizontal Enlrgmt', 'Vertical Enlrgmt', 'Enlargement SQ Footage' ], axis=1)

In [25]:
df.isnull().sum(axis=1)

0        1
1        0
2        0
3        1
4        0
        ..
19608    0
19609    0
19610    0
19611    1
19612    1
Length: 19613, dtype: int64

In [29]:
df[df.isnull().sum(axis=1) > 0]

,Job #,Borough,House #,Street Name,Block,Lot,Bin #,Job Type,Community - Board,Fully Permitted,Initial Cost,Zoning Dist1,Job Description
0,123768976,MANHATTAN,1598,2ND AVENUE,1545,49,1049907,A2,108,NaN,"$65,000.00",C1-9,INTERIOR RENOVATION TO COMBINE APARTMENT 2E AN...
3,301976057,BROOKLYN,1401,OCEAN AVENUE,7584,35,3206621,A2,314,02/28/2006,"$75,000.00",NaN,COMBINING OF APARTMENT 4A &amp; 4L.NO CHANGEIN...
11,302022656,BROOKLYN,6,2 STREET,460,2,3007811,A2,306,04/23/2008,"$60,000.00",NaN,RENOVATE EXISTING LOWER DUPLEX APARTMENT. NO C...
12,102614048,MANHATTAN,730,PARK AVENUE,1385,37,1041333,A2,108,05/10/2000,"$75,000.00",NaN,Minor renovation to existing apartment to incl...
13,302026849,BROOKLYN,1054,WILLOUGHBY AVENUE,3208,11,3325441,A2,304,NaN,"$40,000.00",R6,Application being filed to renovate existing s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19579,104477870,MANHATTAN,160,CENTRAL PARK SOUTH,1011,7501,1023760,A2,105,09/15/2006,"$85,000.00",NaN,RENOVATION OF AN EXISTING APARTMENTON THE 9TH ...
19583,321998326,BROOKLYN,126,DEAN STREET,194,32,3001265,A1,302,NaN,"$40,000.00",R6,REMOVAL AND INSTALLATION OF INTERIOR PARTITION...
19584,302221138,BROOKLYN,234,WASHINGTON AVENUE,1917,32,3055065,A1,302,NaN,"$75,000.00",R6,Proposed to convert one class 'A' apartment an...
19611,200838558,BRONX,2762,KINGSBRIDGE TERRACE,3253,90,2015521,A2,208,NaN,"$40,000.00",R6,Proposed to renovate existing apartments. No c...
19612,301429158,BROOKLYN,802,HOWARD AVENUE,3565,42,3081797,A2,316,NaN,"$60,000.00",R6,PROPOSE RENOVATE EXISTING CLASS 'A' APARTMENT ...

In [ ]:
n_duplicates = df_clean.duplicated().sum()
print(n_duplicates)

6104

In [35]:
df = df.drop_duplicates()

In [38]:
df = df.reset_index(drop=True)

In [39]:
df

,Job #,Borough,House #,Street Name,Block,Lot,Bin #,Job Type,Community - Board,Fully Permitted,Initial Cost,Zoning Dist1,Job Description
0,123768976,MANHATTAN,1598,2ND AVENUE,1545,49,1049907,A2,108,NaN,"$65,000.00",C1-9,INTERIOR RENOVATION TO COMBINE APARTMENT 2E AN...
1,140922893,MANHATTAN,160,E 89 ST,1517,43,1048094,A2,108,07/14/2020,"$85,000.00",R8B,HEREBY FILING APPLICATION FOR THE INTERIOR REN...
2,301773579,BROOKLYN,65,GATES AVENUE,1962,86,3056039,A1,302,05/23/2007,"$60,000.00",R6,Change existing four story and basement brick ...
3,301976057,BROOKLYN,1401,OCEAN AVENUE,7584,35,3206621,A2,314,02/28/2006,"$75,000.00",NaN,COMBINING OF APARTMENT 4A &amp; 4L.NO CHANGEIN...
4,301989276,BROOKLYN,154,NOBLE STREET,2573,10,3065099,A1,301,09/29/2006,"$40,000.00",C4-3,New C of O for existing building. New duplex a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13504,123847409,MANHATTAN,225,CENTRAL PARK WEST,1196,29,1031181,A2,107,06/11/2020,"$60,000.00",R10A,COMBINATION OF APARTMENTS 1608 AND 1610 ON 015...
13505,141021631,MANHATTAN,51,5TH AVENUE,569,5,1009275,A2,102,12/09/2022,"$40,000.00",R10,LEVEL 2 RENOVATIONS: PARTIAL REMOVAL OF NON-ST...
13506,121090112,MANHATTAN,110,DUANE STREET,150,22,1001645,A2,101,07/17/2012,"$40,000.00",C6-2A,APARTMENT RENVOATION AT APT #4R. DEMOLISH AND ...
13507,102937342,MANHATTAN,166,BANK STREET,638,4,1078335,A2,102,02/07/2001,"$80,000.00",C6-2,Interior renovation of an existing apartment. ...
13508,301429158,BROOKLYN,802,HOWARD AVENUE,3565,42,3081797,A2,316,NaN,"$60,000.00",R6,PROPOSE RENOVATE EXISTING CLASS 'A' APARTMENT ...